java_library(
    name = "collectionsTemplate-src",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
      #  "@maven//:org_apache_commons_commons_lang3",
       # "@maven//:com_google_guava_guava",
    ],
)