java_library(
    name = "collectionsTemplate-test",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//inf/collectionsTemplate/src/main/java:collectionsTemplate-src",
       # "//inf/collections/src:collections-src",

        "@maven//:org_junit_jupiter_junit_jupiter_api",
       # "@maven//:junit_junit",
        "@maven//:net_jqwik_jqwik_api",
        "@maven//:org_apache_commons_commons_lang3",
       # "@maven//:com_google_guava_guava",
       # "@maven//:org_assertj_assertj_core",
    ],
)

